services:
  # Backend API service
  - type: web
    name: instafollowx-api
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  # Frontend static site
  - type: static
    name: instafollowx-web
    env: static
    region: singapore
    buildCommand: npm install && npm run build
    publishPath: build
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    autoDeploy: true
